### PR TITLE
fixes #475 LruMap putIfAbsent behaves correctly when maximumSize = 1

### LINKED ISSUE #475: LruMap of maximumSize 1 crashes on second insert
```dart
import 'package:quiver/collection.dart' show LruMap;

void main() {
  final map = LruMap<int, String>(maximumSize: 1);
  map.putIfAbsent(7, () => 'seven');
  map.putIfAbsent(8, () => 'eight');
}
```

```none
$ dart --version
Dart VM version: 2.0.0-dev.69.2 (Mon Jul 23 17:10:56 2018 +0200) on "macos_x64"
srawlins-macbookair:dart-quiver srawlins$ dart a.dart 
Unhandled exception:
NoSuchMethodError: The setter 'next=' was called on null.
Receiver: null
Tried calling: next=null
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      LinkedLruHashMap._removeLru (file:///Users/srawlins/code/dart-quiver/lib/src/collection/lru_map.dart:379:11)
#2      LinkedLruHashMap.putIfAbsent (file:///Users/srawlins/code/dart-quiver/lib/src/collection/lru_map.dart:182:7)
#3      main (file:///Users/srawlins/code/dart-quiver/a.dart:6:7)
#4      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:279:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

### PR DESCRIPTION
**Pull request by wills**

### CODE REVIEW

**Comment by wills** [comment]
I signed it.

**Comment by cbracken** [comment]
> Googler, please make sure the reason for overriding the CLA status is clearly documented in these comments.

The additional commit comes from a Googler (cbracken@google.com / chris@bracken.jp).

**Comment by cbracken** [comment]
> Googler, please make sure the reason for overriding the CLA status is clearly documented in these comments.

The additional commit comes from a Googler (cbracken@google.com / chris@bracken.jp). Also cleaned up duplicate bot comments.

**Comment by cbracken** [comment]
@wills thanks for this PR and apologies we failed to deal with it for so long. Most of the authors were busy working on getting Flutter 1.0 launched at the time... and some things that should not have been forgotten were lost. History became legend. Legend became myth. And for 12 and a half months the PR passed out of all knowledge until, when chance came, it ensnared a new reviewer.

This patch looks good to me. I've added a very small tweak after thinking about this a little. In your unit test, setting the max size to 1 removes A and B, which leaves head == tail == C. When we insert B, we add it to the entries, then call removeLru. removeLru ends up setting tail to tail.previous, which is null, but when that happens, we should really null-out head since we've removed the last element. Doing that work there is then sufficient to
